<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-31 19:41
=======
# Generated by Django 4.2.16 on 2024-09-18 15:09
>>>>>>> 4e6b3bb (docker)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
